{% set data = load_setuptools()%}

package:
    name: obvious-ci
    version: {{data.get('version')}}

source:
    path: ../

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - setuptools
        - binstar
        - conda
        - conda-build
