package:
    name: obvious-ci
    version: '0.1.dev'

source:
    path: ../

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - setuptools
        - binstar
        - conda
        - conda-build
